"""Persistence gateways. Plain protocols, no base-class hierarchy."""

from __future__ import annotations

from typing import Protocol

from frank.domain.model.book import BookStatus, BookStructure
from frank.domain.model.run import Run, RunFailure, RunTally


class RunRepository(Protocol):
    def start(self, book_id: str) -> Run: ...
    def record_success(self, tally: RunTally) -> Run: ...
    def record_failure(self, failure: RunFailure) -> Run: ...
    def get(self, run_id: str) -> Run: ...


class BookRepository(Protocol):
    def save_structure(self, structure: BookStructure) -> None: ...
    def get_structure(self, slug: str) -> BookStructure: ...
    def set_status(self, slug: str, status: BookStatus) -> None: ...
