"""Persistence gateways. Plain protocols, no base-class hierarchy."""

from __future__ import annotations

from typing import Protocol

from frank.domain.model.annotation import Annotation, GlossDecision, SenseUnit, Token
from frank.domain.model.book import (
    BookStatus,
    BookStructure,
    Chapter,
    Passage,
    Sentence,
)
from frank.domain.model.lemma import LemmaOverride
from frank.domain.model.reunion import VerbParticle
from frank.domain.model.run import Run, RunFailure, RunTally
from frank.domain.model.termbase import AddressPair, Character, StyleCard, Term


class RunRepository(Protocol):
    def start(self, book_id: str) -> Run: ...
    def record_success(self, tally: RunTally) -> Run: ...
    def record_failure(self, failure: RunFailure) -> Run: ...
    def get(self, run_id: str) -> Run: ...


class BookRepository(Protocol):
    def save_structure(self, structure: BookStructure) -> None: ...
    def get_structure(self, slug: str) -> BookStructure: ...
    def set_status(self, slug: str, status: BookStatus) -> None: ...
    def replace_annotation(self, slug: str, annotation: Annotation) -> None: ...
    def get_sentences(self, slug: str) -> tuple[Sentence, ...]: ...
    def get_tokens(self, slug: str) -> tuple[Token, ...]: ...
    def get_particles(self, slug: str) -> tuple[VerbParticle, ...]: ...
    def get_sense_units(self, slug: str) -> tuple[SenseUnit, ...]: ...
    def get_gloss_plan(self, slug: str) -> tuple[GlossDecision, ...]: ...
    def replace_passages(self, slug: str, structure: BookStructure) -> None: ...
    def get_passages(self, slug: str) -> tuple[Passage, ...]: ...
    def replace_overrides(
        self, slug: str, overrides: tuple[LemmaOverride, ...]
    ) -> None: ...
    def get_overrides(self, slug: str) -> tuple[LemmaOverride, ...]: ...
    def set_chapter_summaries(
        self, slug: str, chapters: tuple[Chapter, ...]
    ) -> None: ...


class TermbaseRepository(Protocol):
    def replace_terms(self, slug: str, terms: tuple[Term, ...]) -> None: ...
    def get_terms(self, slug: str) -> tuple[Term, ...]: ...
    def replace_characters(
        self, slug: str, characters: tuple[Character, ...]
    ) -> None: ...
    def get_characters(self, slug: str) -> tuple[Character, ...]: ...
    def replace_address_pairs(
        self, slug: str, pairs: tuple[AddressPair, ...]
    ) -> None: ...
    def get_address_pairs(self, slug: str) -> tuple[AddressPair, ...]: ...
    def replace_style_card(self, slug: str, card: StyleCard) -> None: ...
    def get_style_card(self, slug: str) -> StyleCard | None: ...
